category: IT Services
commonfields:
  id: MicrosoftGraphApplications
  version: -1
configuration:
- defaultvalue: 6b071e63-f701-454b-9e54-ede4c96483e6
  display: Application ID
  hidden: false
  name: app_id
  required: true
  type: 0
- display: Trust any certificate (not secure)
  name: insecure
  required: false
  type: 8
- display: Use system proxy settings
  name: proxy
  required: false
  type: 8
description: Use the Microsoft Graph Applications integration to manage authorized
  application.
display: Microsoft Graph Applications
name: MicrosoftGraphApplications
script:
  commands:
  - deprecated: false
    description: Run this command to start the authorization process and follow the
      instructions in the command results.
    execution: false
    name: msgraph-apps-auth-start
  - deprecated: false
    description: Run this command to complete the authorization process. Should be
      used after running the msgraph-apps-auth-start command.
    execution: false
    name: msgraph-apps-auth-complete
  - deprecated: false
    description: Run this command if for some reason you need to rerun the authentication
      process.
    execution: false
    name: msgraph-apps-auth-reset
  - deprecated: false
    description: Tests connectivity to Microsoft.
    execution: false
    name: msgraph-apps-auth-test
  - deprecated: false
    description: Retrieve a list of service principals.
    execution: false
    name: msgraph-apps-service-principal-list
    arguments:
    - name: limit
      default: false
      description: Maximum results to fetch. 0 is all.
      isArray: false
      required: false
      defaultValue: 10
      secret: false
    outputs:
    - contextPath: MSGraphService.accountEnabled
      description: 'true if the service principal account is enabled; otherwise, false.'
      type: Boolean
    - contextPath: MSGraphService.appDescription
      description: A brief description of the app.
      type: String
    - contextPath: MSGraphService.appDisplayName
      description: 'The display name exposed by the associated application.'
      type: String
    - contextPath: MSGraphService.appId
      description: 'The unique identifier for the associated application (its appId
        property).'
      type: String
    - contextPath: MSGraphService.appOwnerOrganizationId
      description: 'Contains the tenant id where the application is registered. This
        is applicable only to service principals backed by applications.'
      type: String
    - contextPath: MSGraphService.appRoleAssignmentRequired
      description: 'Specifies whether users or other service principals need to be
        granted an app role assignment for this service principal before users can
        sign in or apps can get tokens. The default value is false.'
      type: Boolean
    - contextPath: MSGraphService.applicationTemplateId
      description: 'Unique identifier of the applicationTemplate that the servicePrincipal
        was created from. Read-only.'
      type: String
    - contextPath: MSGraphService.createdDateTime
      description: 'Time which the application created.'
      type: Date
    - contextPath: MSGraphService.deletedDateTime
      description: 'Time which the application deleted.'
      type: Date
    - contextPath: MSGraphService.description
      description: A brief description of the app.
      type: String
    - contextPath: MSGraphService.displayName
      description: 'The display name for the service principal.'
      type: String
    - contextPath: MSGraphService.homepage
      description: 'Home page or landing page of the application.'
      type: String
    - contextPath: MSGraphService.id
      description: 'The unique identifier for the service principal.'
      type: String
    - contextPath: MSGraphService.info.logoUrl
      description: CDN URL to the application's logo,
      type: String
    - contextPath: MSGraphService.info.marketingUrl
      description: Link to the application's marketing page.
      type: String
    - contextPath: MSGraphService.info.privacyStatementUrl
      description: Link to the application's privacy statement.
      type: String
    - contextPath: MSGraphService.info.supportUrl
      description: Link to the application's support page.
      type: String
    - contextPath: MSGraphService.info.termsOfServiceUrl
      description: Link to the application's terms of service statement.
      type: String
    - contextPath: MSGraphService.loginUrl
      description: Specifies the URL where the service provider redirects the user
        to Azure AD to authenticate. Azure AD uses the URL to launch the application
        from Microsoft 365 or the Azure AD My Apps
      type: String
    - contextPath: MSGraphService.logoutUrl
      description: Specifies the URL that will be used by Microsoft's authorization
        service to logout an user.
      type: String
    - contextPath: MSGraphService.notes
      description: Application's notes.
      type: String
    - contextPath: MSGraphService.oauth2PermissionScopes.adminConsentDescription
      description: A description of the delegated permissions, intended to be read
        by an administrator granting the permission on behalf of all users. This text
        appears in tenant-wide admin consent experiences.
      type: String
    - contextPath: MSGraphService.oauth2PermissionScopes.adminConsentDisplayName
      description: The permission's title, intended to be read by an administrator
        granting the permission on behalf of all users.
      type: String
    - contextPath: MSGraphService.oauth2PermissionScopes.id
      description: Unique delegated permission identifier inside the collection of
        delegated permissions defined for a resource application.
      type: String
    - contextPath: MSGraphService.oauth2PermissionScopes.isEnabled
      description: Is oauth2PermissionScopes enabled or not.
      type: Boolean
    - contextPath: MSGraphService.oauth2PermissionScopes.type
      description: Specifies whether this delegated permission should be considered
        safe for non-admin users to consent to on behalf of themselves, or whether
        an administrator should be required for consent to the permissions.
      type: String
    - contextPath: MSGraphService.oauth2PermissionScopes.userConsentDescription
      description: A description of the delegated permissions, intended to be read
        by a user granting the permission on their own behalf. This text appears in
        consent experiences where the user is consenting only on behalf of themselves.
      type: String
    - contextPath: MSGraphService.oauth2PermissionScopes.userConsentDisplayName
      description: A title for the permission,
      type: String
    - contextPath: MSGraphService.oauth2PermissionScopes.value
      description: Specifies the value to include in the scope claim in access tokens.
      type: String
    - contextPath: MSGraphService.preferredSingleSignOnMode
      description: Specifies the single sign-on mode configured for this application.
        Azure AD uses the preferred single sign-on mode to launch the application
        from Microsoft 365 or the Azure AD My Apps. The supported values are password,
        saml, external, and oidc.
      type: String
    - contextPath: MSGraphService.preferredTokenSigningKeyThumbprint
      description: Thumbprint of preferred certificate to sign the token
      type: String
    - contextPath: MSGraphService.replyUrls
      description: The URLs that user tokens are sent to for sign in with the associated
        application, or the redirect URIs that OAuth 2.0 authorization codes and access
        tokens are sent to for the associated application.
      type: String
    - contextPath: MSGraphService.samlSingleSignOnSettings
      description: The collection for settings related to saml single sign-on.
      type: String
    - contextPath: MSGraphService.servicePrincipalNames
      description: Contains the list of identifiersUris,
      type: String
    - contextPath: MSGraphService.servicePrincipalType
      description: Identifies if the service principal represents an application or
        a managed identity.
      type: String
    - contextPath: MSGraphService.signInAudience
      description: The audience that can sign in.
      type: String
    - contextPath: MSGraphService.tokenEncryptionKeyId
      description: Specifies the keyId of a public key from the keyCredentials
      type: String
    - contextPath: MSGraphService.verifiedPublisher.addedDateTime
      description: The timestamp when the verified publisher was first added or most
        recently updated.
      type: Date
    - contextPath: MSGraphService.verifiedPublisher.displayName
      description: The verified publisher name from the app publisher's Partner Center
        account.
      type: String
    - contextPath: MSGraphService.verifiedPublisher.verifiedPublisherId
      description: The ID of the verified publisher from the app publisher's Partner
        Center account.
      type: String
  - deprecated: false
    description: Removes an app from the directory.
    execution: false
    name: msgraph-apps-service-principal-remove
    arguments:
    - name: id
      default: false
      description: The ID of the service to remove. Can be retrieved via msgraph-apps-service-principal-remove
        command.
      isArray: false
      required: true
      secret: false
  isfetch: false
  runonce: false
  script: '-'
  type: python
  subtype: python3
  dockerimage: demisto/crypto:1.0.0.14297
fromversion: 5.0.0
tests:
- MSGraph Applications Test
